##@ Development

.PHONY: release
release: test package index ## Execute both package and index

.PHONY: index
index: ## Generate an index file using helm
	@sh -c "'$(CURDIR)/scripts/helm-index.sh'"

.PHONY: package
package: ## Package all charts into a versioned chart archive files
	@sh -c "'$(CURDIR)/scripts/helm-package.sh'"

.PHONY: test
test: ## Test a chart by render templates locally
	@sh -c "'$(CURDIR)/scripts/helm-test.sh'"
