apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ required "namespace is missing" .Values.namespace }}
data:
  # ---------------------------------------------------------------------------
  # Configuration.
  # ---------------------------------------------------------------------------
  spotinst.cluster-identifier: {{ required "spotinst.clusterIdentifier is missing" .Values.spotinst.clusterIdentifier }}
  base-url: {{ default "" .Values.spotinst.baseUrl | quote }}
  proxy-url: {{ default "" .Values.spotinst.proxyUrl | quote }}
  disable-auto-update: {{ default "false" .Values.spotinst.disableAutoUpdate | quote }}
  enable-csr-approval: {{ default "false" .Values.spotinst.enableCsrApproval | quote }}
