apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ required "namespace is missing" .Values.namespace }}
data:
  # ---------------------------------------------------------------------------
  # Credentials.
  #
  # TODO(liran): Remove the `spotinst.` prefix.
  # ---------------------------------------------------------------------------
  spotinst.token: {{ required "spotinst.token is missing" .Values.spotinst.token }}
  spotinst.account: {{ required "spotinst.account is missing" .Values.spotinst.account }}
  # ---------------------------------------------------------------------------
  # Configuration.
  # ---------------------------------------------------------------------------
  spotinst.cluster-identifier: {{ required "spotinst.clusterIdentifier is missing" .Values.spotinst.clusterIdentifier }}
  base-url: {{ default "" .Values.spotinst.baseUrl | quote }}
  proxy-url: {{ default "" .Values.spotinst.proxyUrl | quote }}
  {{- if eq .Values.namespace "kube-system" }}
  disable-auto-update: {{ default "false" .Values.spotinst.disableAutoUpdate | quote }}
  {{- else }}
  disable-auto-update: "true"
  {{- end }}
  enable-csr-approval: {{ default "false" .Values.spotinst.enableCsrApproval | quote }}
