{{- if and .Values.aksConnector.enabled .Values.aksConnector.acdIdentifier }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ocean-controller.aksConnectorJobName" . }}
  namespace: {{ include "ocean-controller.namespace" . }}
  labels:
  {{- include "ocean-controller.commonLabels" . | nindent 4 }}
  {{- include "ocean-controller.aksConnectorLabels" . | nindent 4 }}
  annotations:
  {{- include "ocean-controller.customAnnotations" . | nindent 4 }}
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
      {{- include "ocean-controller.aksConnectorLabels" . | nindent 8 }}
      annotations:
      {{- include "ocean-controller.customAnnotations" . | nindent 8 }}
    spec:
      {{- if .Values.aksConnector.nodeSelector }}
      nodeSelector: {{ toYaml .Values.aksConnector.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.aksConnector.image.pullSecrets }}
      imagePullSecrets: {{ toYaml .Values.aksConnector.image.pullSecrets | nindent 6 }}
      {{- else if .Values.image.pullSecrets }}
      imagePullSecrets: {{ toYaml .Values.image.pullSecrets | nindent 6 }}
      {{- end }}
      containers:
      - name: ocean-aks-connector
        image: {{ .Values.aksConnector.image.repository }}
        imagePullPolicy: {{ .Values.aksConnector.image.pullPolicy }}
        args: ["connect-ocean"]
        env:
        - name: SPOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "ocean-controller.secretName" . }}
              key: token
        - name: SPOT_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: {{ include "ocean-controller.secretName" . }}
              key: account
        - name: SPOT_CLUSTER_IDENTIFIER
          value: {{ required "`spotinst.clusterIdentifier` must be specified" .Values.spotinst.clusterIdentifier }}
        - name: SPOT_ACD_IDENTIFIER
          value: {{ .Values.aksConnector.acdIdentifier }}
        {{- if .Values.resources }}
        resources: {{ toYaml .Values.resources | nindent 10 }}
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        volumeMounts:
        - name: waagent
          mountPath: /var/lib/waagent
      volumes:
      - name: waagent
        hostPath:
          path: /var/lib/waagent
          type: Directory
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- if .Values.dnsConfig }}
      dnsConfig: {{ toYaml .Values.dnsConfig | nindent 8 }}
      {{- end }}
      tolerations: {{ toYaml .Values.aksConnector.tolerations | nindent 6 }}
      restartPolicy: Never
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ocean-controller.secretName" . }}
  namespace: {{ include "ocean-controller.namespace" . }}
  labels:
  {{- include "ocean-controller.commonLabels" . | nindent 4 }}
  {{- include "ocean-controller.aksConnectorLabels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "4"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
type: Opaque
data:
  token: {{ required "`spotinst.token` must be specified" .Values.spotinst.token | b64enc }}
  account: {{ required "`spotinst.account` must be specified" .Values.spotinst.account | b64enc }}
{{- end }}
