{{- if and (not .Values.credentialsSecret.useExisting) .Values.credentialsSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentialsSecret.name | default .Chart.Name | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
type: Opaque
data:
  account: {{ .Values.spotinst.account | b64enc | quote }}
  token: {{ .Values.spotinst.token | b64enc | quote }}
{{- end -}}
