{{- if and ( not .Values.spotinst.credentialsSecret.useExisting ) .Values.spotinst.credentialsSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.spotinst.credentialsSecret.name | default .Chart.Name | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
type: Opaque
data:
  account: {{ required "spotinst.account is missing" .Values.spotinst.account | b64enc | quote }}
  token: {{ required "spotinst.token is missing" .Values.spotinst.token | b64enc | quote }}
{{- end -}}
