# Default values for spotinst-kubernetes-cluster-controller.

# Default namespace.
namespace: kube-system

# Spotinst configuration.
spotinst:
  # Credentials, see: https://api.spotinst.com/spotinst-api/administration/create-an-api-token.
  token: ""
  account: ""

  # Will put credentials in k8s secrets instead of ConfigMap
  credentialsSecret:
    # disabled for backward compatibility
    enabled: false

    # custom name for secret
    # name: spotinst-creds

    # existing secret will be used
    # useExisting: true

  # Configuration.
  clusterIdentifier: ""
  baseUrl: ""
  proxyUrl: ""
  disableAutoUpdate: false
  enableCsrApproval: false

# Metrics Server configuration.
metrics-server:
  deployChart: true
  args:
  - --logtostderr
  # enable this if you have self-signed certificates, see: https://github.com/kubernetes-incubator/metrics-server
  #  - --kubelet-insecure-tls

# Resource requests and limits.
# ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources: {}
  # If you do want to specify resources, uncomment the following lines,
  # adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

# Image.
# ref: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: spotinst/kubernetes-cluster-controller
  pullPolicy: Always

# DNS policy.
# ref: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
dnsPolicy: ClusterFirst

# DNS config.
# ref: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/
dnsConfig:
  options:
  - name: ndots
    value: "1"

# Tolerations for nodes that have taints on them.
# ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations:
- key: node.kubernetes.io/not-ready
  effect: NoExecute
  operator: Exists
  tolerationSeconds: 150
- key: node.kubernetes.io/unreachable
  effect: NoExecute
  operator: Exists
  tolerationSeconds: 150
- key: node-role.kubernetes.io/master
  operator: Exists

# Pod scheduling preferences.
# ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      preference:
        matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: Exists
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 50
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: k8s-app
            operator: In
            values:
            - spotinst-kubernetes-cluster-controller
        topologyKey: kubernetes.io/hostname
