# -- Default namespace. (Optional)
namespace: kube-system

# -- configure the amount of replicas for the controller (Optional)
replicas: 1
# -- Annotations for ocean-controller deployment (Optional)
deploymentAnnotations: {}

# -- Additional environment variables for ocean-controller deployment (Optional)
# Should contain `name` and `value` for each element
deploymentEnv: []
#  - name: envName
#    value: envValue

# Configuration.
spotinst:
  # -- Spot Token. (Required)
  # Ref: https://docs.spot.io/administration/api/create-api-token
  token: ""
  # -- Spot Account. (Required)
  # Ref: https://docs.spot.io/administration/organizations?id=account
  account: ""
  # -- Unique identifier used by the Ocean Controller to connect (Required)
  # between the Ocean backend and the Kubernetes cluster.
  # Ref: https://docs.spot.io/ocean/tutorials/spot-kubernetes-controller/
  clusterIdentifier: ""
  # -- Base URL. (Optional)
  baseUrl: ""
  # -- Proxy URL. (Optional)
  proxyUrl: ""
  # -- Disable auto update. (Optional)
  disableAutoUpdate: false
  # -- Enable CSR approval. (Optional)
  enableCsrApproval: false

# Secret.
# Ref: https://kubernetes.io/docs/concepts/configuration/secret/
secret:
  # -- Use a Secret instead of a ConfigMap to store credentials. Disabled for backward compatibility. (Optional)
  enabled: false
  # -- Controls whether a Secret should be created. (Optional)
  create: true
  # -- Secret name. (Optional)
  name: spotinst-kubernetes-cluster-controller

# CA bundle.
# Ref: https://kubernetes.io/docs/concepts/configuration/secret/
caBundleSecret:
  # -- Secret name. (Optional)
  name: spotinst-kubernetes-cluster-controller-ca-bundle

# Config Map.
# Ref: https://kubernetes.io/docs/concepts/configuration/configmap/
configMap:
  # -- Controls whether a ConfigMap should be created. (Optional)
  create: true
  # -- ConfigMap name. (Optional)
  name: spotinst-kubernetes-cluster-controller-config

# Service Account.
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
serviceAccount:
  # -- Controls whether a ServiceAccount should be created. (Optional)
  create: true
  # -- Service account name. (Optional)
  name: spotinst-kubernetes-cluster-controller

# -- Resource requests and limits. (Optional)
# Ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources: {}
  # If you do want to specify resources, uncomment the following lines,
  # adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

# Image.
# Ref: https://kubernetes.io/docs/concepts/containers/images/
image:
  # -- Image repository. (Optional)
  repository: gcr.io/spotinst-artifacts/kubernetes-cluster-controller
  # -- Image pull policy. (Optional)
  pullPolicy: Always
  # -- Image pull secrets. (Optional)
  pullSecrets: []

# -- DNS policy. (Optional)
# Ref: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
dnsPolicy: Default

# -- DNS config. (Optional)
# Ref: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/
dnsConfig: {}
  # options:
  # - name: ndots
  #   value: "1"

# -- Tolerations for nodes that have taints on them. (Optional)
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations:
- key: node.kubernetes.io/not-ready
  effect: NoExecute
  operator: Exists
  tolerationSeconds: 150
- key: node.kubernetes.io/unreachable
  effect: NoExecute
  operator: Exists
  tolerationSeconds: 150
- key: node-role.kubernetes.io/master
  operator: Exists
- key: node-role.kubernetes.io/control-plane
  operator: Exists
- key: CriticalAddonsOnly
  operator: Exists

# Pod scheduling preferences.
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity:
  # -- Node affinity. (Optional)
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: NotIn
          values:
          - windows
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      preference:
        matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: Exists
  # -- Pod anti-affinity. (Optional)
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 50
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: k8s-app
            operator: In
            values:
            - spotinst-kubernetes-cluster-controller
        topologyKey: kubernetes.io/hostname

# Ocean AKS Connector.
aksConnector:
  # -- Controls whether the Ocean AKS Connector should be deployed (Optional)
  # (requires a valid `aksConnector.acdIdentifier`).
  enabled: true
  # -- Unique identifier used by the Ocean AKS Connector when (Optional)
  # importing an AKS cluster.
  acdIdentifier: ""
  # -- Job name. (Optional)
  jobName: spotinst-kubernetes-cluster-controller-aks-connector
  # -- Resource requests and limits. (Optional)
  # Ref: http://kubernetes.io/docs/user-guide/compute-resources/
  resources: {}
    # If you do want to specify resources, uncomment the following lines,
    # adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi
  # Image.
  # Ref: https://kubernetes.io/docs/concepts/containers/images/
  image:
    # -- Image repository. (Optional)
    repository: spotinst/ocean-aks-connector:1.0.8
    # -- Image pull policy. (Optional)
    pullPolicy: Always
    # -- Image pull secrets. (Optional)
    pullSecrets: []
  # -- Tolerations for nodes that have taints on them. (Optional)
  # Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations:
  # Allow the connector to be rescheduled while the node is in "critical add-ons only" mode.
  - key: CriticalAddonsOnly
    operator: Exists
  # -- Node selection constraints. (Optional)
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
  nodeSelector:
    kubernetes.azure.com/mode: system

# Metrics Server configuration.
metrics-server:
  # -- Specifies whether the metrics-server chart should be deployed. (Optional)
  deployChart: true
  # -- Arguments to pass to metrics-server on start up. (Optional)
  args:
  - --logtostderr
  # enable this if you have self-signed certificates, see: https://github.com/kubernetes-incubator/metrics-server
  #  - --kubelet-insecure-tls
